global:
  configMapName: "quizguru-prod-configmap"
  activeProfile: "prod"
  rabbitmqUsername: "guest"
  rabbitmqPass: "guest"
  keycloakUrl: "http://identity:8080/realms/Quizguru/protocol/openid-connect/certs"
  configServerURl: "configserver:http://config-server:8888/"
  mysqlPass: "k989898k"
  keycloakAdminUsername: "admin"
  keycloakAdminPassword: "admin"
  keycloakDBName: "mysql"
  keycloakDBUsername: "root"
  keycloakDBPassword: "k989898k"
  keycloakDBURL: "jdbc:mysql://mysql/keycloak"
  eurekaServerURL: "http://eureka:8761/eureka/"
  openTelemetryJavaAgent: "-javaagent:/opentelemetry-javaagent.jar"
  otelEndpoint: "http://tempo:4317"
  otelMetricsExporter: "none"
  otelLogsExporter: "none"
  otelProtocol: "grpc"