CREATE DATABASE IF NOT EXISTS quizguru_library;
CREATE DATABASE IF NOT EXISTS quizguru_quiz;
CREATE DATABASE IF NOT EXISTS quizguru_record;
CREATE DATABASE IF NOT EXISTS quizguru_generate;
CREATE DATABASE IF NOT EXISTS keycloak;