services:
  network-base-config:
    networks:
      - quizguru

  microservice-base-config:
    extends:
      service: network-base-config

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      - SPRING_PROFILES_ACTIVE=${profile_default}
      - SPRING_CONFIG_IMPORT

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
