services:
  network-base-config:
    networks:
      - quizguru

  microservice-base-config:
    extends:
      service: network-base-config
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/opentelemetry-javaagent.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    volumes:
      - ../libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
