services:
  network-base-config:
    networks:
      - quizguru

  microservice-base-config:
    extends:
      service: network-base-config
    deploy:
      resources:
        limit:
          memory: 500M

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
