CREATE DATABASE IF NOT EXISTS quizguru_auth;
CREATE DATABASE IF NOT EXISTS quizguru_library;
CREATE DATABASE IF NOT EXISTS quizguru_quiz;
CREATE DATABASE IF NOT EXISTS quizguru_record;
CREATE DATABASE IF NOT EXISTS quizguru_user;
CREATE DATABASE IF NOT EXISTS quizguru_generate;