deploymentName: libraries-deployment
serviceName: libraries
appLabel: libraries
appName: libraries

replicaCount: 1

image:
  repository: nguyenduckhai/library
  tag: 1.0

containerPort: 8084

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: false