services:
  network-base-config:
    networks:
      - quizguru

  microservice-base-config:
    extends:
      service: network-base-config
    environment:
      - JAVA_TOOL_OPTIONS
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_METRICS_EXPORTER
      - OTEL_LOGS_EXPORTER
      - OTEL_EXPORTER_OTLP_PROTOCOL
    volumes:
      - ../libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      - SPRING_PROFILES_ACTIVE:=${PROFILE_PROD}
      - SPRING_CONFIG_IMPORT

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
